name: proto_checks

on: [pull_request]

jobs:
  proto_checks:
    name: proto lint and breaking changes detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }}'